### ISSUE TITLE
[Question] LightGBM GPU version for setuptools

### ISSUE THREAD

**Issue by bingoko** [lightgbm-org/LightGBM#4653]
Hi,

I would like to include "lightgbm --install-options=--gpu" in the install_requires in setup.py for building wheel.
However, install_requires argument doesn't allow --install-option.

Any solution to that?

**Comment by StrikerRUS** [comment]
I'm going to close this issue as the original feature request should be redirected to the `setuptools` project.

If you have any further suggestions for `lightgbm-gpu` package, please feel free to share them in #2263.
