### ISSUE TITLE
[dask] lightgbm + dask generates crazy predictions

### ISSUE THREAD

**Issue by szhang5947** [lightgbm-org/LightGBM#4695]
## Description
We are experimenting with distributed learning using lightgbm + dask, and noticed that the predictions could be obviously wrong (crazy numbers). For the reproducible example below, the `r_squared` of the in-sample prediction using lightgbm + dask is -1.5e+56. As comparison, training on local machine without distributed learning generates a reasonable prediction with `r_squared` ~ 0.01. 

## Reproducible example
Given that a dask `client` has already been created,
```
import numpy as np
import pandas as pd
import dask
import lightgbm as lgb
import sklearn

# Prepare data
train_data = pd.read_csv("train_data.csv")
train_data_dask = dask.dataframe.from_pandas(train_data, npartitions=2)
X_train = train_data_dask[["x0", "x1"]].to_dask_array(lengths=True)
y_train = train_data_dask["y"].to_dask_array(lengths=True)
w_train = train_data_dask["weight"].to_dask_array(lengths=True)

# Model training and in-sample prediction
model = lgb.DaskLGBMRegressor(
    client=client,
    max_depth=8,
    learning_rate=0.01,
    tree_learner="data",
    n_estimators=500,
)

model.fit(X_train, y_train, sample_weight=w_train)
y_pred = model.predict(X=X_train)

# Measure the result using r_squared
y_local = y_train.compute()
w_local = w_train.compute()
y_pred_local = y_pred.compute()

r_squared = sklearn.metrics.r2_score(y_local, y_pred_local, sample_weight=w_local)
print(f"r_squared: {r_squared}")
```

Output:
```
r_squared: -1.4827682862501415e+56
```

## Environment info
`dask` version: 2021.05.1
`lightgbm` version: 3.2.1

## Dataset
[train_data.csv](https://github.com/microsoft/LightGBM/files/7369639/train_data.csv)

**Comment by jmoralez** [comment]
Could you upgrade `lightgbm` to 3.3.0 and try it? I believe this has been fixed.
