### ISSUE TITLE
Wrong doc for `categorical_feature`

### ISSUE THREAD

**Issue by PhilipMay** [lightgbm-org/LightGBM#5016]
In the parameter doc here: https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.rst

you say that `categorical_feature` can be set to `categorical_feature=name:c1,c2,c3`.

1. from Python perspective this would be a syntax error
2. even `categorical_feature="name:c1,c2,c3"` would be wrong
3. I think `categorical_feature=["name:c1", "name:c2", "name:c3"]` would be right

**Comment by StrikerRUS** [comment]
Hey @PhilipMay ! Thanks for bringing this question up!

The document you are referring is mainly for the CLI LightGBM version. It is supposed that for Python and R packages users use corresponding to each package documentation. For example, docstrings for Python-package clearly explain how to use `categorical_feature` argument in Python: 
> **categorical_feature** *(list of str or int, or 'auto', optional (default="auto"))* – Categorical features. If list of int, interpreted as indices. If list of str, interpreted as feature names (need to specify `feature_name` as well). If ‘auto’ and data is pandas DataFrame, pandas unordered categorical columns are used.
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Dataset.html#lightgbm.Dataset

However, that way of specifying categorical features described in the general doc for all params you're referring is correct for Python package as well and can be used during loading data from file. Consider checking the following example:
```python
import lightgbm as lgb

datafile_name = r"train_data.txt"
dataset_params = {
    'header': True,
    "categorical_feature": "name:c1,c2,c3"
}
lgb_data = lgb.Dataset(datafile_name, params=dataset_params)

train_params = {
    'objective': 'multiclass',
    'num_classes': 5,
    'verbose': -1
}
bst = lgb.train(train_params, lgb_data, num_boost_round=3)

model_dump = bst.dump_model()
assert model_dump['feature_infos']['c2']['values'] == [-1, 0, 1]
```

[train_data.txt](https://github.com/microsoft/LightGBM/files/8101357/train_data.txt)
