### ISSUE TITLE
About feval's bug

### ISSUE THREAD

**Issue by sunkun1997** [lightgbm-org/LightGBM#5476]
## Description
I want to use the optimal F1 score as the evaluation function, but there was a bug

## Reproducible example
```
import numpy as np
from sklearn.metrics import f1_score
def lgb_evaluate_func(pre, train):
    labels = train.get_label()
    best_f1 = 0
    for threshold in [0.5, 0.6, 0.7]:
        pre = np.where(pre >= threshold , 1, 0)
        f1 = f1_score(pre, labels)
        if f1 > best_f1:
            best_f1 = f1
    return 'best_f1', best_f1 , True
```
However, all the thresholds give the same value

I need to use the following code to get the correct result
```
def lgb_evaluate_func(pre, train):
    labels = train.get_label()
    f1 = [f1_score(np.where(pre >= 0.5, 1, 0), labels), f1_score(np.where(pre >= 0.6, 1, 0), labels), 
        f1_score(np.where(pre >= 0.7, 1, 0), labels)]
    return 'best_f1', max(f1), True
```

## Environment info

LightGBM version or commit hash:
Python lightgbm package, the version is 3.3.2

**Comment by jmoralez** [comment]
You're overwriting the value of `pre` in `pre = np.where(pre >= threshold , 1, 0)`. You should use a different variable there.

**Comment by sunkun1997** [comment]
@jmoralez Thank you very much! That's my problem.
